wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1666133726
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 19
      4: 3.9.12
      5: 0.12.20
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
embedding_dims:
  desc: null
  value: 10
epochs:
  desc: null
  value: 10
filters:
  desc: null
  value: 16
hidden_dims:
  desc: null
  value: 250
kernel_size:
  desc: null
  value: 3
maxlen:
  desc: null
  value: 30
vocab_size:
  desc: null
  value: 2000
